import test from 'node:test';import assert from 'node:assert/strict';import {freshProgress,validateProgress,completeStep,xpFor,streakFor} from '../src/lib/progress.ts';import {commandFor,voiceError} from '../src/lib/voice.ts';import {projectFiles,projectZip} from '../src/lib/project-export.mjs';import {addControl,updateControl,validateForm} from '../src/designer-engine.mjs';import {unzipSync,strFromU8} from 'fflate';import {lessons} from '../src/curriculum.ts';
test('curriculum contains unique lessons and complete coding challenges',()=>{assert.equal(lessons.length,21);assert.equal(new Set(lessons.map(l=>l.id)).size,21);for(const lesson of lessons){if(lesson.kind==='code'){assert.ok(lesson.prediction);for(const c of [lesson.build,lesson.apply]){assert.ok(c.harness&&c.expected&&c.solution&&c.starter);assert.notEqual(c.solution,c.starter);}}else assert.equal(lesson.questions.length,4);}});
test('XP is earned once and progress can be validated and restored',()=>{let p=freshProgress();p=completeStep(p,'variables','0');p=completeStep(p,'variables','0');assert.equal(xpFor(p),20);p=completeStep(p,'variables','4',true);p=completeStep(p,'variables','4',true);assert.equal(xpFor(p),100);assert.ok(validateProgress(JSON.parse(JSON.stringify(p))));assert.equal(validateProgress({...p,settings:{...p.settings,rate:90}}),false);assert.equal(validateProgress({...p,drafts:{bad:{html:'<script>'}}}),false);});
test('streak counts real consecutive local days',()=>assert.equal(streakFor(['2026-10-05','2026-10-06'],new Date(2026,9,7)),2));
test('voice commands are constrained to navigation and stop',()=>{assert.equal(commandFor('open designer'),'designer');assert.equal(commandFor('Open code lab!'),'playground');assert.equal(commandFor('delete all files'),null);assert.match(voiceError('not-allowed'),/permission was denied/);assert.match(voiceError('network'),/connect/);});
test('native ZIP includes editable project, solution, event handlers and escaped strings',()=>{const controls=updateControl(addControl([], 'Button'),'button1',{name:'btnSave',eventClick:'btnSave_Click',text:'Say "hello"'});const files=projectFiles(controls);assert.ok(files['CodeQuestForms.sln']);assert.match(files['Form1.cs'],/void btnSave_Click/);assert.match(files['Form1.Designer.cs'],/Controls.Add/);const zip=unzipSync(projectZip(controls));assert.match(strFromU8(zip['CodeQuestForms.csproj']),/net8.0-windows/);});
test('reserved C# names and invalid numeric ranges prevent export',()=>{assert.equal(validateForm(updateControl(addControl([],'Label'),'label1',{name:'class'})).ok,false);assert.equal(validateForm(updateControl(addControl([],'NumericUpDown'),'numericupdown1',{minimum:10,maximum:1})).ok,false);});

test("export rejects handler collisions with fields and generated members",()=>{const controls=addControl([],"Button");assert.equal(validateForm([{...controls[0],eventClick:controls[0].name}]).ok,false);assert.equal(validateForm([{...controls[0],name:"Form1",eventClick:"Save_Click"}]).ok,false);});
