export const toolbox=["Label","TextBox","Button","ComboBox","ListBox","RadioButton","CheckBox","NumericUpDown"];export const categories=["Appearance","Behavior","Data","Design","Layout","Accessibility","Events"];
const defaults={font:"Segoe UI, 9pt",foreColor:"#000000",backColor:"#f0f0f0",enabled:true,visible:true,tabIndex:0,anchor:"Top, Left",dock:"None",accessibleName:"",eventClick:"",eventTextChanged:""};
export function addControl(list,type){if(!toolbox.includes(type))throw new Error("Unsupported control type");let n=1;while(list.some(x=>x.id===type.toLowerCase()+n||x.name===type.toLowerCase()+n))n++;return[...list,{id:type.toLowerCase()+n,type,name:type.toLowerCase()+n,text:type,x:30+(n-1)*12,y:30+(n-1)*12,width:type==="TextBox"?180:110,height:type==="ListBox"?90:34,...defaults,tabIndex:list.length}]}
export function updateControl(list,id,patch){patch={...patch};delete patch.id;delete patch.type;for(const k of ["x","y","width","height","tabIndex"]){if(k in patch){const n=Number(patch[k]);patch[k]=Number.isFinite(n)?Math.max(k==="width"?24:k==="height"?20:0,Math.round(n)):0;}}return list.map(x=>x.id===id?{...x,...patch}:x)}export function removeControl(list,id){return list.filter(x=>x.id!==id)}export function moveControl(list,id,x,y){return updateControl(list,id,{x:Math.max(0,x),y:Math.max(0,y)})}export function resizeControl(list,id,width,height){return updateControl(list,id,{width:Math.max(24,width),height:Math.max(20,height)})}
export function validateForm(list){const issues=[];const names=list.map(x=>x.name);if(new Set(names).size!==names.length)issues.push("Control names must be unique.");for(const c of list){if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(c.name))issues.push(c.name+": invalid C# control name.");for(const k of ["eventClick","eventTextChanged"]){if(c[k]&&!/^[A-Za-z_][A-Za-z0-9_]*$/.test(c[k]))issues.push(c.name+": invalid event handler name.");}if(c.type==="Button"&&!c.eventClick)issues.push(c.name+": wire a Click event.");}return{ok:issues.length===0,issues}}
const quote=value=>JSON.stringify(String(value)).replace(/\\u2028/g,"\\u2028");
export function designerCode(list){return list.map(c=>{
 const target=`this.${c.name}`;
 const lines=[`${target} = new System.Windows.Forms.${c.type}();`,`${target}.Location = new System.Drawing.Point(${c.x}, ${c.y});`,`${target}.Name = ${quote(c.name)};`,`${target}.Size = new System.Drawing.Size(${c.width}, ${c.height});`,`${target}.Text = ${quote(c.text)};`,`${target}.Enabled = ${c.enabled};`,`${target}.Visible = ${c.visible};`,`${target}.TabIndex = ${c.tabIndex};`,`${target}.AccessibleName = ${quote(c.accessibleName)};`];
 for(const key of ["foreColor","backColor"])lines.push(`${target}.${key==="foreColor"?"ForeColor":"BackColor"} = System.Drawing.ColorTranslator.FromHtml(${quote(c[key])});`);
 const font=/^(.+),\s*(\d+(?:\.\d+)?)pt$/.exec(c.font);
 if(font)lines.push(`${target}.Font = new System.Drawing.Font(${quote(font[1])}, ${font[2]}F);`);
 lines.push(`${target}.Anchor = ${c.anchor.split(",").map(a=>`System.Windows.Forms.AnchorStyles.${a.trim()}`).join(" | ")};`,`${target}.Dock = System.Windows.Forms.DockStyle.${c.dock};`);
 for(const [property,event] of [["eventClick","Click"],["eventTextChanged","TextChanged"]])if(c[property])lines.push(`${target}.${event} += new System.EventHandler(this.${c[property]});`);
 lines.push(`this.Controls.Add(${target});`);
 return lines.join("\n");
 }).join("\n\n")}
